name: Golangci-lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go/go.mod
    - name: Analysing the code with golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        working-directory: go
        version: latest
